### PR TITLE
styling changes for global settings

### PR DESCRIPTION
**Pull request by mul1sh**
Fixes the issues noted by @anjj123  [here](https://github.com/GetSpeckle/speckle-browser-extension/pull/115#issuecomment-531612546)

### CODE REVIEW

**Comment by mul1sh** [comment]
@anjj123 @mytechtip @fyang1024 any feedback on this, thanks 🙂

**Comment by fyang1024** [comment]
It looks Okay for me.

**Comment by anjj123** [comment]
@mul1sh it's a bit too clustered on the right, I added an image as a general visual guide as to where the dropdown menu should be moved to the left, so we can free up some space on the right side of the toolbar and add more space between the icons (and move the speckle logo more to the left too). We should be good after this. I'll @w3f in the original issue list to close the bounty
banner

**Comment by fyang1024** [comment]
@anjj123 @mul1sh  it'll be hard to make the layout look perfect using Grid. By "perfect" I mean, spaces between elements are even and margins on both sides are symmetric, while keeping the network dropdown at the center. You can probably change the network names shorter in networks.ts, Kusama CC1 -> Kusama, Edgeware(test) -> Edgeware, then you can set the columns of the 4 elements to 4, 7, 2, 2. @anjj123 to make the margins symmetric, we probably need to remove the border of the rightmost icon when it's not activated.

**Comment by mul1sh** [comment]
I agree with @fyang1024 achieving perfect symmetry with the current grid is going to be impossible @anjj123 

Unless maybe I remove the grid component all together and maybe introduce a styled component that displays the top menu bar items in a flex box and spaces them evenly according to their size. Thats the only way I see this working well.

**Comment by fyang1024** [comment]
> I agree with @fyang1024 achieving perfect symmetry with the current grid is going to be impossible @anjj123
> 
> Unless maybe I remove the grid component all together and maybe introduce a styled component that displays the top menu bar items in a flex box and spaces them evenly according to their size. Thats the only way I see this working well.

@mul1sh agreed. We will appreciate that if you could try replacing grid with flex box to layout top menu items.

**Comment by mul1sh** [comment]
> @mul1sh agreed. We will appreciate that if you could try replacing grid with flex box to layout top menu items.

Cool on it, will push the flex box in a few hours then :)

**Comment by anjj123** [comment]
@mul1sh hey just checking if you were able to do this. also, one other tiny fix - on firefox the words "log out" exceed the box. can you make this slightly smaller so it fits?

**Comment by mul1sh** [comment]
@anjj123  sorry got a bit delayed on this, but sure I'll fix it in the next few hours + the mozilla issue and alert you to test 🙂

**Comment by anjj123** [comment]
@mul1sh any updates here? Thanks

**Comment by mul1sh** [comment]
@anjj123 yes still working on it, sorry for the delay, I've been a bit caught on my end but expect a commit fixing all these bugs tomorrow.

**Comment by anjj123** [comment]
@mul1sh checking in again. let us know if you need anything

**Comment by anjj123** [comment]
@mul1sh checking in again

**Comment by mul1sh** [comment]
@anjj123  sorry been abit busy 😐  but will sort it out, over the weekend. By Monday it will be ready.

**Pull request merged**
